### ISSUE TITLE
Shell theme problems Ubuntu 20.04

### ISSUE THREAD

**Issue by AJJLagerweij** [godlyranchdressing/United-GNOME#184]
Hello,

I'm not sure why this is the case but there are issues with the shell theme on ubuntu 19s.
I've appended a couple of screenshots.

First there seems to be an issue with the font size in the search menu:
![Schermafdruk van 2019-10-19 13-51-02](https://user-images.githubusercontent.com/31255888/67143782-b00a3600-f277-11e9-821e-469c9b143c03.png)

Secondly the fonts in some of the dropdown menu seems to be wrong, do also note the colour of the sliders.
![Schermafdruk van 2019-10-19 13-51-27](https://user-images.githubusercontent.com/31255888/67143798-d8923000-f277-11e9-9e02-5d5759316b27.png)

Problems with the volume setting indicator.
![Schermafdruk van 2019-10-19 13-51-36](https://user-images.githubusercontent.com/31255888/67143800-dd56e400-f277-11e9-9aef-fab1a3dd263d.png)

I'm not sure how to resolve this myself, but I would love to use this awesome theme.
Is the project still active?
Regards.

**Comment by AJJLagerweij** [comment]
Dear everyone, I'm a total noob to this, but I have decided to try and fix the shell such that it can be used for ubuntu 20.04.

Because I have 0 knowledge of how this all works I will simply go through the gnome-shell.css file by hand and fix issues that I find. My fixes will thus be accompanied by snippets of .css code and explanations what they do/fix. You have to go to your own gnome-shell.css and apply the fix if you want to. My examples are for the ubuntu alt Dark and Light themes. However, it should be easy to adapt the snippets into the version of the theme that you are using.

This is just the first fix, there are more to come!

OSD overlays with weird shadows.
---------------------------------------------
Old:
![afbeelding](https://user-images.githubusercontent.com/31255888/101147312-42f96180-362d-11eb-8f99-11e7cfe3413b.png)

New:
![afbeelding](https://user-images.githubusercontent.com/31255888/101147453-720fd300-362d-11eb-8dee-af470afd7dc9.png)


Volume Bar Colour:
Old:
```css
.osd-window .level {
  height: 0.3em;
  border-radius: 6px;
  background-color: rgba(94, 94, 94, 0.75);
  color: #5e5e5e;
}
```

New:
```css
.osd-window .level {
  height: 1em;
  border-radius: 6px;
  -barlevel-background-color: #c7c7c7;
  -barlevel-active-background-color: #5E5E5E;
  -barlevel-overdrive-color: #991121;
  -barlevel-overdrive-separator-width: 3px;
}
```
Shadows:
Old:
```css
.modal-dialog, .end-session-dialog, .show-processes-dialog,
.mount-question-dialog, .prompt-dialog, .audio-device-selection-dialog, .access-dialog, .geolocation-dialog, .osd-window,
.resize-popup,
.switcher-list, .workspace-switcher-container, .nm-dialog, .login-dialog {
  color: #5e5e5e;
  border-image: url("assets/osd_background.svg") 40 40 40 40;
  border-width: 24px;
}
```
New:
```css
.modal-dialog, .end-session-dialog, .show-processes-dialog,
.mount-question-dialog, .prompt-dialog, .audio-device-selection-dialog, .access-dialog, .geolocation-dialog, .osd-window,
.resize-popup,
.switcher-list, .workspace-switcher-container, .nm-dialog, .login-dialog {
  color: #5e5e5e;
  border-image: url("assets/osd_background.svg") 40 40 40 40;
  border-width: 24px;
  box-shadow: none;
}
```

**Comment by AJJLagerweij** [comment]
# Toggles with appropriate image
Don't mind the change in highlight, colours, I compare here my fixed alt Light theme to the ubuntu Light theme.
The fix is related to the toggle image.

Old:
![afbeelding](https://user-images.githubusercontent.com/31255888/101149115-8c4ab080-362f-11eb-8ff2-4d3dce90d6fa.png)

New:
![afbeelding](https://user-images.githubusercontent.com/31255888/101149291-c87e1100-362f-11eb-878a-05740439e4db.png)

Old code:
```css
.toggle-switch {
  width: 48px;
  height: 20px;
  background-size: contain;
}
```
New:
```css
.toggle-switch {
  width: 48px;
  height: 20px;
  background-size: contain;
  background-image: url("assets/toggle-off.svg");
}

.toggle-switch:checked {
  background-image: url("assets/toggle-on.svg");
}
```

**Comment by AJJLagerweij** [comment]
# Weird large letters in overview search
I guess that this is intended as a feature, but for me the font type is simply to large, especially on 1080p screens.
I reduced the font size of the search results from 18pt to 12pt, but you can of course choose your own font-size, see the first fix.
Afterwards, I decided to increase the other fonts in the same menu from 10.5pt (default) to 12pt because of personal taste, this required me to add the ```css fontsize: 12pt;``` to many of the other lines, see fix 2.

Old:
![Schermafdruk van 2020-12-04 13-00-59](https://user-images.githubusercontent.com/31255888/101150178-f44dc680-3630-11eb-8f64-7b9792bab213.png)

New:
![Schermafdruk van 2020-12-04 13-01-44](https://user-images.githubusercontent.com/31255888/101150184-f6b02080-3630-11eb-956c-ee2f939a6f64.png)

## Reduce the big search title font
Old code:
```css
.list-search-result-title {
  font-size: 18pt;
  font-weight: 400;
  color: #ffffff;
}
```
New:
```css
.list-search-result-title {
  font-size: 12pt;
  font-weight: 400;
  color: #ffffff;
}
```

## Increasing the other fonts in the overview search results
Old Code
```css
.search-provider-icon:focus, .search-provider-icon:selected, .search-provider-icon:hover, .search-provider-icon:active, .search-provider-icon:checked,
.list-search-result:focus,
.list-search-result:selected,
.list-search-result:hover,
.list-search-result:active,
.list-search-result:checked {
  box-shadow: inset 0 0px 0px 1px rgba(17, 17, 17, 0.1);
}

.search-provider-icon:focus, .search-provider-icon:selected, .search-provider-icon:hover,
.list-search-result:focus,
.list-search-result:selected,
.list-search-result:hover {
  background-color: rgba(255, 255, 255, 0.2);
  transition-duration: 150ms;
}

.search-provider-icon:active, .search-provider-icon:checked,
.list-search-result:active,
.list-search-result:checked {
  background-color: rgba(255, 255, 255, 0.1);
  transition-duration: 250ms;
}

.app-well-app .overview-icon,
.app-well-app.app-folder .overview-icon,
.grid-search-result .overview-icon {
  box-shadow: inset 0 0px 0px 1px rgba(17, 17, 17, 0.1);
}

.app-well-app:hover .overview-icon,
.app-well-app:focus .overview-icon,
.app-well-app:selected .overview-icon,
.app-well-app.app-folder:hover .overview-icon,
.app-well-app.app-folder:focus .overview-icon,
.app-well-app.app-folder:selected .overview-icon,
.grid-search-result:hover .overview-icon,
.grid-search-result:focus .overview-icon,
.grid-search-result:selected .overview-icon {
  background-color: rgba(255, 255, 255, 0.2);
  box-shadow: inset 0 0px 0px 1px rgba(17, 17, 17, 0.1);
  transition-duration: 0s;
  border-image: none;
  background-image: none;
}

.app-well-app:active .overview-icon,
.app-well-app:checked .overview-icon,
.app-well-app.app-folder:active .overview-icon,
.app-well-app.app-folder:checked .overview-icon,
.grid-search-result:active .overview-icon,
.grid-search-result:checked .overview-icon {
  background-color: rgba(255, 255, 255, 0.1);
  box-shadow: inset 0 0px 0px 1px rgba(17, 17, 17, 0.1);
  transition-duration: 250ms;
}

.app-well-app-running-dot {
  width: 24px;
  height: 2px;
  background-color: #A42435;
  margin-bottom: 1px;
}

.search-provider-icon,
.list-search-result, .app-well-app .overview-icon,
.app-well-app.app-folder .overview-icon,
.grid-search-result .overview-icon {
  color: #ffffff;
  border-radius: 6px;
  padding: 6px;
  border: none;
  transition-duration: 250ms;
  text-align: center;
}
```
New:
```css
.search-provider-icon:focus, .search-provider-icon:selected, .search-provider-icon:hover, .search-provider-icon:active, .search-provider-icon:checked,
.list-search-result:focus,
.list-search-result:selected,
.list-search-result:hover,
.list-search-result:active,
.list-search-result:checked {
  box-shadow: inset 0 0px 0px 1px rgba(17, 17, 17, 0.1);
  font-size: 12pt;
}

.search-provider-icon:focus, .search-provider-icon:selected, .search-provider-icon:hover,
.list-search-result:focus,
.list-search-result:selected,
.list-search-result:hover {
  background-color: rgba(255, 255, 255, 0.2);
  transition-duration: 150ms;
  font-size: 12pt;
}

.search-provider-icon:active, .search-provider-icon:checked,
.list-search-result:active,
.list-search-result:checked {
  background-color: rgba(255, 255, 255, 0.1);
  transition-duration: 250ms;
  font-size: 12pt;
}

.app-well-app .overview-icon,
.app-well-app.app-folder .overview-icon,
.grid-search-result .overview-icon {
  box-shadow: inset 0 0px 0px 1px rgba(17, 17, 17, 0.1);
  font-size: 12pt;
}

.app-well-app:hover .overview-icon,
.app-well-app:focus .overview-icon,
.app-well-app:selected .overview-icon,
.app-well-app.app-folder:hover .overview-icon,
.app-well-app.app-folder:focus .overview-icon,
.app-well-app.app-folder:selected .overview-icon,
.grid-search-result:hover .overview-icon,
.grid-search-result:focus .overview-icon,
.grid-search-result:selected .overview-icon {
  background-color: rgba(255, 255, 255, 0.2);
  box-shadow: inset 0 0px 0px 1px rgba(17, 17, 17, 0.1);
  transition-duration: 0s;
  border-image: none;
  background-image: none;
  font-size: 12pt;
}

.app-well-app:active .overview-icon,
.app-well-app:checked .overview-icon,
.app-well-app.app-folder:active .overview-icon,
.app-well-app.app-folder:checked .overview-icon,
.grid-search-result:active .overview-icon,
.grid-search-result:checked .overview-icon {
  background-color: rgba(255, 255, 255, 0.1);
  box-shadow: inset 0 0px 0px 1px rgba(17, 17, 17, 0.1);
  transition-duration: 250ms;
  font-size: 12pt;
}

.app-well-app-running-dot {
  width: 24px;
  height: 2px;
  background-color: #A42435;
  margin-bottom: 1px;
}

.search-provider-icon,
.list-search-result, .app-well-app .overview-icon,
.app-well-app.app-folder .overview-icon,
.grid-search-result .overview-icon {
  color: #ffffff;
  border-radius: 6px;
  padding: 6px;
  border: none;
  transition-duration: 250ms;
  text-align: center;
  font-size: 12pt;
}
```

**Comment by AJJLagerweij** [comment]
# Fixing the calendar (and weather)
The calendar in the panel looks horrible in the dark mode, but when I compare it to the screenshots in the `more-previews` folder of there seem to be issues with the light mode as well.

Old:
![afbeelding](https://user-images.githubusercontent.com/31255888/101159830-151d1880-363f-11eb-8e88-9e77f6ba3511.png)

New:
![afbeelding](https://user-images.githubusercontent.com/31255888/101159862-21a17100-363f-11eb-90e5-6a4121f00d79.png)

## Calendar
Old code:
```css
.calendar {
  margin-bottom: 0;
}
```
New:
```css
.calendar {
  margin-bottom: 0;
  border-width: 0pt;
  background-color: transparent;
}
```

## Weather and today button
Old code:
```css
.datemenu-today-button,
.world-clocks-button,
.weather-button,
.events-section-title, .message-list-section-title {
  border-radius: 6px;
  color: #ffffff;
}
```
New:
```css
.datemenu-today-button,
.world-clocks-button,
.weather-button,
.events-section-title, .message-list-section-title {
  border-radius: 6px;
  border-width: 0pt;
  color: #ffffff;
  background-color: transparent;
}
```

## Remaining issues (Dark mode only)
When comparing the new dark mode to the new light mode it becomes apparent that some text is indistinguishable from the background. This is the text of the:
- Media control,
- Notification content and,
- Weather time.
Although the text is readable in the light theme, it is still the wrong font colour, it should be dark grey, not entirely black.

![afbeelding](https://user-images.githubusercontent.com/31255888/101160340-f1a69d80-363f-11eb-893f-00a8361fc70d.png)

I expected to influence the colours in, for example:
```css
.message-content {
  min-height: 44px;
  padding: 8px;
  color: rgba(255, 255, 255, 0.75);
  font-size: 1em;
}
```
but that does not seem to be the case. I'll look a t this at a later date.

**Comment by AJJLagerweij** [comment]
# Problems with the Dark Shell theme
Some text remains 'black' in already dark menus and is hence unreadable.

Old:
![afbeelding](https://user-images.githubusercontent.com/31255888/101160982-f455c280-3640-11eb-902a-39a7a9d20238.png)

New:
![afbeelding](https://user-images.githubusercontent.com/31255888/101161035-03d50b80-3641-11eb-8fb8-d6502e559d32.png)

## Dark menu should have light text font fix
Old Code:
```css
.popup-menu {
  min-width: 200px;
  border-radius: 6px !important;
  border: 1px solid rgba(244, 244, 244, 0.1);
}

.popup-menu {
  box-shadow: inset 0 0 1px #111111, 0 0 1px #111111 !important;
}
```
New:
```css
.popup-menu {
  min-width: 200px;
  border-radius: 6px !important;
  border: 1px solid rgba(244, 244, 244, 0.1);
  color: #ffffff;
  box-shadow: inset 0 0 1px #111111, 0 0 1px #111111 !important;
}
```

**Comment by AJJLagerweij** [comment]
# Fixed themes
Because I wasn't able to salvage the transparent shell theme which was set as the standard option I've decided to switch around a bit what the combinations of shell and gtk themes are. The following files where working on Ubuntu 20.04 and Gnome 3.36. Here I'll upload the files that I edited:

## United Ubuntu
[United-Ubuntu.zip](https://github.com/godlyranchdressing/United-GNOME/files/5760207/United-Ubuntu.zip)
[United-Ubuntu-Compact.zip](https://github.com/godlyranchdressing/United-GNOME/files/5760208/United-Ubuntu-Compact.zip)
[United-Ubuntu-Dark.zip](https://github.com/godlyranchdressing/United-GNOME/files/5760209/United-Ubuntu-Dark.zip)
[United-Ubuntu-Dark-Compact.zip](https://github.com/godlyranchdressing/United-GNOME/files/5760210/United-Ubuntu-Dark-Compact.zip)
[United-Ubuntu-Light.zip](https://github.com/godlyranchdressing/United-GNOME/files/5760211/United-Ubuntu-Light.zip)
[United-Ubuntu-Light-Compact.zip](https://github.com/godlyranchdressing/United-GNOME/files/5760212/United-Ubuntu-Light-Compact.zip)

## United Ubuntu Alternative
[United-Alt.zip](https://github.com/godlyranchdressing/United-GNOME/files/5760214/United-Alt.zip)
[United-Alt-Compact.zip](https://github.com/godlyranchdressing/United-GNOME/files/5760215/United-Alt-Compact.zip)
[United-Alt-Dark.zip](https://github.com/godlyranchdressing/United-GNOME/files/5760216/United-Alt-Dark.zip)
[United-Alt-Dark-Compact.zip](https://github.com/godlyranchdressing/United-GNOME/files/5760217/United-Alt-Dark-Compact.zip)
[United-Alt-Light.zip](https://github.com/godlyranchdressing/United-GNOME/files/5760218/United-Alt-Light.zip)
[United-Alt-Light-Compact.zip](https://github.com/godlyranchdressing/United-GNOME/files/5760219/United-Alt-Light-Compact.zip)

## Notes
I'm aware that there are 2 issues remaining.
1. Some windows keep a dark title bar even when the light theme is selected. (I have no clue how to fix this, and expect that it is not a shell related issue)
2. The application menu is too wide, which is a shell issue but I don't know how to fix this.
![afbeelding](https://user-images.githubusercontent.com/31255888/103456993-638c0880-4d0c-11eb-9785-91ae02677667.png)

## Hosting the git
I'm not forking this project because I don't know how to maintain these in an automated manner. I do not have any source files, the only changes that I made are done by hand on the final .css files. If anyone wants to help me out and introduce me in an automated way I would like to explore it and I would be willing to fork the project and maintain it.

**Comment by AJJLagerweij** [comment]
# Fixed world clock widget
The shell extensions for world clocks was displayed wrongly. The colour of the city, time and time difference was undefined. Adding the following CSS entry below `.world-clocks-grid` fixes it however.
```css
.world-clocks-city, .world-clocks-time, .world-clocks-timezone {
  color: #5e5e5e; /* for the light theme and #ffffff for the dark theme */
}
```
Here are the resulting theme files:
[United-Ubuntu.zip](https://github.com/godlyranchdressing/United-GNOME/files/5897895/United-Ubuntu.zip)
[United-Alt.zip](https://github.com/godlyranchdressing/United-GNOME/files/5897894/United-Alt.zip)
